window.BENCHMARK_DATA = {
  "lastUpdate": 1680120828568,
  "repoUrl": "https://github.com/drcjt/CSharp-80",
  "entries": {
    "CSharp-80 Benchmark": [
      {
        "commit": {
          "author": {
            "email": "5084481+drcjt@users.noreply.github.com",
            "name": "Colin Taylor",
            "username": "drcjt"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "5e64a984c8d1068479617de9f107c63ad150e89d",
          "message": "Try using continuous benchmarking action in workflow (#184)\n\n* Try using continuous benchmarking action in workflow\r\n\r\n* Fix indentation in build workflow yml file\r\n\r\n* Fix whitespace\r\n\r\n* Split build into separate workflows for PRs and pushes to main\r\nMain build now uses gh-pages branch to record results of benchmarks\r\n\r\n---------\r\n\r\nCo-authored-by: Colin Taylor <drcjt@outlook.com>",
          "timestamp": "2023-03-29T21:08:38+01:00",
          "tree_id": "8fe4d44c7fea735de7de7ca5eb1d6bc85e923a7d",
          "url": "https://github.com/drcjt/CSharp-80/commit/5e64a984c8d1068479617de9f107c63ad150e89d"
        },
        "date": 1680120819660,
        "tool": "customSmallerIsBetter",
        "benches": [
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {}
        ]
      }
    ]
  }
}